---
title: "Assam HEC Extraction"
author: "Grace Kumaishi"
date: "7/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(terra)
library(ggplot2)
library(sf)

# Enter YOUR data path to HWC_data folder, including "HWC_data". 
# May require double forward slashes
HWC_data <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data" 
```

### CROPLAND HUMAN ELEPHANT CONFLICT DATA ###

```{r}
# Load historic bivariate SDM vs. cropland

historic_bivariate_asia_new <- terra::rast(here(HWC_data, "/Geospatial Data/bivariate_outputs/asel_bivariate_baseline.tif"))
  
historic_bivariate_asia_project <- terra::project(x = historic_bivariate_asia_new,
                                                  y = "epsg:4326",
                                                  method = "near")

# Load historic Chen LULC raster
historic_chen_raw <- terra::rast(here(HWC_data, "/Geospatial Data/Chen_LULC_data/global_LULC_2015.tif"))

historic_chen <- terra::project(x = historic_chen_raw,
                 y = "epsg:4326", ### THIS TAKES A WHILE!!! you can also use "y = historic_bivariate_asia" which will run faster but is much larger resolution (0.04x0.04 instead of 0.003x0.003) ###
                 method = "near")
  
historic_chen <- terra::project(historic_chen, crs(historic_bivariate_asia), method = "near")

# Load tidy Goalpara HEC file
goalpara_hec_tidy <- read.csv(here(HWC_data, "/Geospatial Data/Assam_India/Goalpara_HEC_tidy.csv"))

# Male into SpatVector
goalpara_hec_tidy_vect <- terra::vect(goalpara_hec_tidy, geom = c("longitude", "latitude"), crs = "epsg:4326")

# Create new Goalpara file with only cropland
goalpara_hec_crop <- goalpara_hec_tidy %>% 
  filter(hec_type == "crop")

# Make into SpatVector
goalpara_hec_crop_vect <- terra::vect(goalpara_hec_crop, geom = c("longitude", "latitude"), crs = "epsg:4326")

# Load tidy Sonitpur file
sonitpur_hec_tidy <- read.csv(here(HWC_data, "/Geospatial Data/Assam_India/Sonitpur_HEC_tidy.csv"))

# Male into SpatVector
sonitpur_hec_tidy_vect <- terra::vect(sonitpur_hec_tidy, geom = c("longitude", "latitude"), crs = "epsg:4326")

# Create new Sonitpur file with only cropland
sonitpur_hec_crop <- sonitpur_hec_tidy %>% 
  filter(hec_type == "crop")
 
# Make into SpatVector
sonitpur_hec_crop_vect <- terra::vect(sonitpur_hec_crop, geom = c("longitude", "latitude"), crs = "epsg:4326")
```

##### HISTORIC CHEN EXTRACTION #####

### GOALPARA ###

```{r}
# CROP only
goalpara_chen_extract <- terra::extract(historic_chen, goalpara_hec_crop_vect, 
                            fun = NULL, 
                            method = "simple",
                            list = FALSE,
                            factors = TRUE) %>% 
  mutate(global_LULC_2015 = as.character(global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "1", "water", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "2", "forest", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "3", "grassland", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "4", "barren", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "5", "cropland", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "6", "urban", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "7", "permanent_snow_ice", global_LULC_2015))

# ALL HEC
goalpara_chen_extract_ALL <- terra::extract(historic_chen, goalpara_hec_tidy_vect, 
                            fun = NULL, 
                            method = "simple",
                            list = FALSE,
                            factors = TRUE) %>% 
  mutate(global_LULC_2015 = as.character(global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "1", "water", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "2", "forest", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "3", "grassland", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "4", "barren", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "5", "cropland", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "6", "urban", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "7", "permanent_snow_ice", global_LULC_2015))

```

```{r}
# Visualize

# Bar chart:
goalpara_chen_bar <- ggplot(data = goalpara_chen_extract, aes(x = fct_infreq(global_LULC_2015), fill = global_LULC_2015)) +
  geom_bar(width = .8, stat = "count") +
  scale_fill_manual(values = c("#646e3b", "#c06636", "#508ea2")) +
  labs(x = "LULC Category",
      y = "Count",
      title = "Goalpara, Assam: Chen HEC Point Extraction (Crop Only)") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) 

goalpara_chen_bar

# Bar chart for ALL
goalpara_chen_bar_ALL <- ggplot(data = goalpara_chen_extract_ALL, aes(x = fct_infreq(global_LULC_2015), fill = global_LULC_2015)) +
  geom_bar(width = .8, stat = "count") +
  scale_fill_manual(values = c("#646e3b", "#c06636", "#508ea2")) +
  labs(x = "LULC Category",
      y = "Count",
      title = "Goalpara, Assam: Chen HEC Point Extraction (ALL)") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) 

goalpara_chen_bar_ALL
```

### SONITPUR ###

```{r}
# CROP only
sonitpur_chen_extract <- terra::extract(historic_chen, sonitpur_hec_crop_vect, 
                            fun = NULL, 
                            method = "simple",
                            list = FALSE,
                            factors = TRUE) %>% 
  mutate(global_LULC_2015 = as.character(global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "1", "water", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "2", "forest", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "3", "grassland", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "4", "barren", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "5", "cropland", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "6", "urban", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "7", "permanent_snow_ice", global_LULC_2015))

# ALL HEC
sonitpur_chen_extract_ALL <- terra::extract(historic_chen, sonitpur_hec_tidy_vect, 
                            fun = NULL, 
                            method = "simple",
                            list = FALSE,
                            factors = TRUE) %>% 
  mutate(global_LULC_2015 = as.character(global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "1", "water", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "2", "forest", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "3", "grassland", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "4", "barren", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "5", "cropland", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "6", "urban", global_LULC_2015),
         global_LULC_2015 = if_else(global_LULC_2015 == "7", "permanent_snow_ice", global_LULC_2015))
```

```{r}
# Visualize

# Bar chart

sonitpur_chen_bar <- ggplot(data = sonitpur_chen_extract, aes(x = fct_infreq(global_LULC_2015), fill = global_LULC_2015)) +
  geom_bar(width = .8, stat = "count") +
  scale_fill_manual(values = c("#646e3b", "#c06636", "#e8b960")) +
  labs(x = "LULC Category",
      y = "Count",
      title = "Sonitpur, Assam: Chen HEC Point Extraction (Crop Only)") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) 

sonitpur_chen_bar

# Bar chart for ALL
sonitpur_chen_bar_ALL <- ggplot(data = sonitpur_chen_extract_ALL, aes(x = fct_infreq(global_LULC_2015), fill = global_LULC_2015)) +
  geom_bar(width = .8, stat = "count") +
  scale_fill_manual(values = c("#646e3b", "#c06636", "#e8b960")) +
  labs(x = "LULC Category",
      y = "Count",
      title = "Goalpara, Assam: Chen HEC Point Extraction (ALL)") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) 

sonitpur_chen_bar_ALL
```

##### NEW BIVARIATE EXTRACTION 8/2/2022 #####

### GOALPARA ###

```{r}
# Extract bivariate at points
goalpara_extract_new <- extract(historic_bivariate_asia_project, goalpara_hec_crop_vect, 
                            fun = NULL, 
                            method = "simple",
                            list = FALSE,
                            factors = TRUE) %>% 
  mutate(indicus_historic = as.character(indicus_historic),
         indicus_historic = if_else(indicus_historic == "20", "no_crop_med_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "21", "med_crop_med_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "22", "high_crop_med_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "30", "no_crop_high_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "31", "med_crop_high_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "32", "high_crop_high_suit", indicus_historic))
```

```{r}
# Visualize 
goalpara_labels_new <- c("High crop \n High suitability", "Medium crop \n High suitability", "High crop \n Medium suitability")

goalpara_chen_bar_new <- ggplot(data = goalpara_extract_new, aes(x = fct_infreq(indicus_historic), fill = indicus_historic)) +
  geom_bar(width = .8, stat = "count") +
  scale_fill_manual(values = c("#351c75ff", "#c27ba0ff", "#b4a7d6ff")) +
  labs(x = "Bivariate Category",
      y = "Count",
      title = "Goalpara, Assam: NEW Bivariate HEC Point Extraction (Crop HEC Only)") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5))  +
  scale_x_discrete(labels= goalpara_labels_new)

goalpara_chen_bar_new
```

### SONITPUR ###

```{r}
# Extract bivariate at points
sonitpur_extract_new <- extract(historic_bivariate_asia_project, sonitpur_hec_crop_vect, 
                            fun = NULL, 
                            method = "simple",
                            list = FALSE,
                            factors = TRUE) %>% 
  mutate(indicus_historic = as.character(indicus_historic),
         indicus_historic = if_else(indicus_historic == "20", "no_crop_med_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "21", "med_crop_med_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "22", "high_crop_med_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "30", "no_crop_high_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "31", "med_crop_high_suit", indicus_historic),
         indicus_historic = if_else(indicus_historic == "32", "high_crop_high_suit", indicus_historic))
```

```{r}
# Visualize 
sonitpur_labels_new <- c("High crop \n Medium suitability", "Medium crop \n Medium suitability")

sonitpur_chen_bar_new <- ggplot(data = sonitpur_extract_new, aes(x = fct_infreq(indicus_historic), fill = indicus_historic)) +
  geom_bar(width = .8, stat = "count") +
  scale_fill_manual(values = c("#c27ba0ff", "#ddddddff")) +
  labs(x = "Bivariate Category",
      y = "Count",
      title = "Sonitpur, Assam: NEW Bivariate HEC Point Extraction (Crop HEC Only)") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  scale_x_discrete(labels= sonitpur_labels_new)

sonitpur_chen_bar_new
```











