---
title: "Assam Chi Square Test"
author: "Grace Kumaishi"
date: "8/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(broom)
library(terra)

# Enter YOUR data path to HWC_data folder, including "HWC_data". 
# May require double forward slashes
HWC_data <- "G:/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data" 
```

## Load in existing data

```{r}
historic_bivariate_asia_raw <- terra::rast(here(HWC_data, "/Geospatial Data/bivariate_outputs/asel_bivariate_baseline.tif"))
  
historic_bivariate_asia_project <- terra::project(x = historic_bivariate_asia_raw,
                                                  y = "epsg:4326",
                                                  method = "near")
```

# CHI SQUARE ON POINT HEC DATA

## Get counts of bivariate category for HEC in Goalpara

```{r}
# Load tidy Goalpara HEC file
goalpara_hec_tidy <- read.csv(here(HWC_data, "/Geospatial Data/Assam_India/Goalpara_HEC_tidy.csv"))

# Make into SpatVector
goalpara_hec_tidy_vect <- terra::vect(goalpara_hec_tidy, geom = c("longitude", "latitude"), crs = "epsg:4326")

# Create new Goalpara file with only cropland
goalpara_hec_crop <- goalpara_hec_tidy %>% 
  filter(hec_type == "crop")

# Make into SpatVector
goalpara_hec_crop_vect <- terra::vect(goalpara_hec_crop, geom = c("longitude", "latitude"), crs = "epsg:4326")
```

```{r}
# Extract bivariate at points
goalpara_hec_extract <- extract(historic_bivariate_asia_project, goalpara_hec_crop_vect, 
                            fun = NULL, 
                            method = "simple",
                            list = FALSE,
                            factors = TRUE) 
```

```{r}
goalpara_hec_extract_count <- goalpara_hec_extract %>% 
  count(indicus_historic) %>% 
  arrange(-n) 
```

## Get counts of bivariate category for random points in Goalpara

```{r}
# Load random Goalpara points
goalpara_random <- terra::vect(here(HWC_data, "/Geospatial Data/Assam_India/random_points_goalpara.shp"), crs = "epsg:4326")
```

```{r}
# Extract bivariate at random points
goalpara_extract_random <- extract(historic_bivariate_asia_project, goalpara_random, 
                            fun = NULL, 
                            method = "simple",
                            list = FALSE,
                            factors = TRUE) 
```

```{r}
goalpara_extract_random_count <- goalpara_extract_random %>% 
  count(indicus_historic) %>% 
  arrange(-n) 
```

## Create table with both extracts by hand

```{r}
bivariate_counts <- data.frame(points = c("HEC", "Random"),
                               med_suit_high_crop = c(14, 46),
                               high_suit_no_crop = c(0, 13),
                               high_suit_med_crop = c(56, 97),
                               high_suit_high_crop = c(273, 187)) 

bivariate_proportions <- bivariate_counts %>% #add proportions/percentages
  janitor::adorn_percentages() %>% 
  janitor::adorn_pct_formatting(digits = 2) %>% 
  janitor::adorn_ns()
```

## Convert to contingency table

```{r}
bivariate_ct <- bivariate_counts %>% 
  column_to_rownames(var = "points")
```

## Run Chi Square test

```{r}
# Are the different point distributions and bivariate categories independent? Are proportions at each category so different that we can conclude there is a significant association of point distribution on the category?

bivariate_x2 <- chisq.test(bivariate_ct)

bivariate_x2

bivariate_tidy <- broom::tidy(bivariate_x2)
```

# CHI SQUARE ON DIGITIZED HEC DATA 

```{r}
# Load in csv with extractions

assam_extract_digitized <- read.csv(here(HWC_data, "/Geospatial Data/Assam_India/assam_points_table_with_conflict.csv"))

assam_summarize_digitized <- assam_extract_digitized %>% 
  group_by(Conflict, Bivar_value) %>% 
  summarise(count = n()) %>% 
  pivot_wider(names_from = Bivar_value, values_from = count)

assam_na_digitized <- head(assam_summarize, -1)

assam_ct_digitized <- assam_na_digitized %>% 
  column_to_rownames(var = "Conflict")
```

```{r}
# Run chi-square test

digitized_x2 <- chisq.test(assam_ct_digitized)

digitized_x2

digitized_tidy <- broom::tidy(digitized_x2)
```

# CHI SQUARE ON GRIDDED HEC DATA 

```{r}
# Load in Assam vector grid

assam_HEC_vect <- vect(paste0(HWC_data, "/Geospatial Data/Assam_India/AWS-all_data/AWS-all_data.shp"))

# Extract bivariate to Assam vector

assam_extract <- extract(historic_bivariate_asia_project, assam_HEC_vect, method = "simple") %>%
  right_join(., as.data.frame(assam_HEC_vect), by = "ID")

assam_summarize <- assam_extract %>% 
  group_by(Conflict, indicus_historic) %>% 
  summarise(count = n()) %>% 
  pivot_wider(names_from = indicus_historic, values_from = count)

assam_remove_na <- head(assam_summarize, -1) %>%
  select(1:6)

assam_ct <- assam_remove_na %>% 
  column_to_rownames(var = "Conflict")
```

```{r}
# Run chi-square test

gridded_x2 <- chisq.test(assam_ct)

gridded_x2

gridded_tidy <- broom::tidy(gridded_x2)
```





