---
title: "HWC Occurrence Wrangling"
author: "Grace Kumaishi"
date: "7/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(tmap)
library(MetBrewer)
library(here)

# Enter YOUR data path to HWC_data folder, including "HWC_data". 
# May require double forward slashes
HWC_data <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data" 
```

```{r}
### Read in the HEC data:

# Goalpara
goalpara_HEC_raw <- read.csv(here(HWC_data, "/Geospatial Data/Assam_India/Goalpara_HEC.csv"))

# Sonitpur
sonitpur_HEC_raw <- read.csv(here(HWC_data, "/Geospatial Data/Assam_India/Sonitpur_HEC.csv")) 
```

### Goalpara District, Assam, India ###

```{r}
### Tidy the Goalpara data ###

# Rename columns and remove unnecessary columns
goalpara_HEC_renamed <- goalpara_HEC_raw %>% 
  select(Date_, 
         latitudeDD, 
         LongitudeD, 
         Prescense.Type...Crop.Damage, 
         Prescense.Type...Elephant.Death.or.Injury, 
         Prescense.Type...Human.Death.or.Injury, 
         Prescense.Type...Property.Damage) %>% 
  rename(date = Date_, 
         latitude = latitudeDD, 
         longitude = LongitudeD, 
         crop = Prescense.Type...Crop.Damage, 
         property = Prescense.Type...Property.Damage, 
         human_death_injury = Prescense.Type...Human.Death.or.Injury, 
         elephant_death_injury = Prescense.Type...Elephant.Death.or.Injury)

# Change blank cells to "NA"
goalpara_HEC_renamed[goalpara_HEC_renamed == ""] <- NA
goalpara_HEC_renamed[goalpara_HEC_renamed == " "] <- NA

# Use pivot_longer to create a single HEC column 
goalpara_HEC_longer <- goalpara_HEC_renamed %>% 
  pivot_longer(cols = 4:7,
               names_to = "hec_type",
               values_drop_na = TRUE)

# Remove extra "value" column
goalpara_HEC_tidy <- goalpara_HEC_longer %>% 
  select(-last_col())
```

```{r}
### Save tidy data set to Google Drive ###

write_csv(goalpara_HEC_tidy, here(HWC_data, "/Geospatial Data/Assam_India/Goalpara_HEC_tidy.csv"))
```

```{r}
### Visualize the Goalpara data

# Map
goalpara_HEC_sf <- st_as_sf(x = goalpara_HEC_tidy,
                            coords = c("longitude", "latitude"),
                            crs = 4326)

tmap_mode(mode = "view")

goalpara_HEC_map <- 
  tm_shape(goalpara_HEC_sf) +
  tm_symbols(col = "hec_type",
             size = 0.2)

goalpara_HEC_map
```

```{r}
# Plot

HEC_labels <- c("Crop", "Property", "Human Death \n or Injury", "Elephant Death \n or Injury")

ggplot(goalpara_HEC_tidy, aes(x = fct_infreq(hec_type))) +
  geom_bar(aes(fill = hec_type),
           stat = "count") +
  scale_fill_manual(values = c("#646e3b", "#c06636", "#802417", "#e8b960")) +
  labs(x = "HEC type",
       y = "Count",
       title = "Frequency of HEC type in Goalpara, Assam") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  scale_x_discrete(labels= HEC_labels)
```

### Sonitpur District, Assam, India ###

```{r}
### Tidy the Sonitpur data ###

# Rename columns and remove unnecessary columns
sonitpur_HEC_renamed <- sonitpur_HEC_raw %>% 
  select(Date_, 
         latitudeDD, 
         LongitudeD, 
         Prescense.Type...Crop.Damage, 
         Prescense.Type...Elephant.Death.or.Injury, 
         Prescense.Type...Human.Death.or.Injury, 
         Prescense.Type...Property.Damage) %>% 
  rename(date = Date_, 
         latitude = latitudeDD, 
         longitude = LongitudeD, 
         crop = Prescense.Type...Crop.Damage, 
         property = Prescense.Type...Property.Damage, 
         human_death_injury = Prescense.Type...Human.Death.or.Injury, 
         elephant_death_injury = Prescense.Type...Elephant.Death.or.Injury)

# Change blank cells to "NA"
sonitpur_HEC_renamed[sonitpur_HEC_renamed == ""] <- NA
sonitpur_HEC_renamed[sonitpur_HEC_renamed == " "] <- NA

# Use pivot_longer to create a single HEC column
sonitpur_HEC_longer <- sonitpur_HEC_renamed %>% 
  pivot_longer(cols = 4:7,
               names_to = "hec_type",
               values_drop_na = TRUE)

# Remove extra "value" column
sonitpur_HEC_tidy <- sonitpur_HEC_longer %>% 
  select(-last_col())
```

```{r}
### Save tidy data set to Google Drive ###

write_csv(sonitpur_HEC_tidy, here(HWC_data, "/Geospatial Data/Assam_India/Sonitpur_HEC_tidy.csv"))
```

```{r}
### Visualize the Sonitpur data

# Map
sonitpur_HEC_sf <- st_as_sf(x = sonitpur_HEC_tidy,
                            coords = c("longitude", "latitude"),
                            crs = 4326)

tmap_mode(mode = "view")

sonitpur_HEC_map <- 
  tm_shape(sonitpur_HEC_sf) +
  tm_symbols(col = "hec_type",
             size = 0.2)

sonitpur_HEC_map
```

```{r}
# Plot

ggplot(sonitpur_HEC_tidy, aes(x = fct_infreq(hec_type))) +
  geom_bar(aes(fill = hec_type),
           stat = "count") +
  scale_fill_manual(values = c("#646e3b", "#c06636", "#802417", "#e8b960")) +
  labs(x = "HEC type",
       y = "Count",
       title = "Frequency of HEC type in Sonitpur, Assam") +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  scale_x_discrete(labels= HEC_labels)
```














