---
title: "Asia MESS Analysis"
author: "Grace Kumaishi"
date: "7/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(raster)
library(modEvA)
library(here)

# Enter YOUR data path to HWC_data folder, including "HWC_data". 
# May require double forward slashes
HWC_data <- "G:/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data" 
```

```{r}
# Call CHELSA data from Google Drive and stack aggregated CHELSA data

chelsa_aggregated_stack <- stack(paste0(HWC_data, "/Data/Chelsa_Data/asia_masked_CHELSA_data/asia_masked_CHELSA_layer", c("01","02","04","06","07","12","14","15"), ".tif"))

### Load thinned occurrence points

thinned_all_spp_occs_xy <- read.csv(here(HWC_data, "/Asia_MESS_analysis/input_dataframes/thinned_occs.csv"))

### Load subspecies coords

all_subspecies_coords <- read.csv(here(HWC_data, "/Asia_MESS_analysis/input_dataframes/all_subspecies_coords.csv"))

# need just lat/long values in two columns to use raster extract
thinned_all_spp_occs_xy <- all_subspecies_coords[c('longitude', 'latitude')]

# extracting values
thinned_all_species_extract <- raster::extract(chelsa_aggregated_stack, thinned_all_spp_occs_xy)

# save as dataframe
write.csv(thinned_all_species_extract, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/historic_extract.csv"), row.names = TRUE)
```

```{r}
### Load in historic dataframe and edit column names

historic <- read.csv(here(HWC_data, "/Asia_MESS_analysis/input_dataframes/historic_extract.csv"))

historic <- historic %>% 
  subset(select = -X) %>% 
  rename(chelsa01 = asia_masked_CHELSA_layer01) %>% 
  rename(chelsa02 = asia_masked_CHELSA_layer02) %>% 
  rename(chelsa04 = asia_masked_CHELSA_layer04) %>% 
  rename(chelsa06 = asia_masked_CHELSA_layer06) %>% 
  rename(chelsa07 = asia_masked_CHELSA_layer07) %>% 
  rename(chelsa12 = asia_masked_CHELSA_layer12) %>% 
  rename(chelsa14 = asia_masked_CHELSA_layer14) %>% 
  rename(chelsa15 = asia_masked_CHELSA_layer15)

write.csv(historic, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/historic_extract_updated_names.csv"), row.names = TRUE)
```

####### 2071-2100 #######

#### 585 ####
### GFDL_ESM4 ###

```{r}
### Call Chelsa Data 
gfdl_2071_2100_585_stack <- stack(paste0(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/GFDL_ESM4/gfdl_2071_2100_585_bio", c("1","2","4","6","7","12","14","15"), ".tif"))

# Extract values
gfdl_2071_2100_585_extract <- raster::extract(gfdl_2071_2100_585_stack, thinned_all_spp_occs_xy)

# save as dataframe
write.csv(gfdl_2071_2100_585_extract, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/GFDL_ESM4/gfdl_2071_2100_585_extract.csv"), row.names = TRUE)
```

```{r}
### Load in dataframe and edit column names

gfdl_2071_2100_585 <- read.csv(here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/GFDL_ESM4/gfdl_2071_2100_585_extract.csv"))

gfdl_2071_2100_585 <- gfdl_2071_2100_585 %>% 
  subset(select = -X) %>% 
  rename(chelsa01 = gfdl_2071_2100_585_bio1) %>% 
  rename(chelsa02 = gfdl_2071_2100_585_bio2) %>% 
  rename(chelsa04 = gfdl_2071_2100_585_bio4) %>% 
  rename(chelsa06 = gfdl_2071_2100_585_bio6) %>% 
  rename(chelsa07 = gfdl_2071_2100_585_bio7) %>% 
  rename(chelsa12 = gfdl_2071_2100_585_bio12) %>% 
  rename(chelsa14 = gfdl_2071_2100_585_bio14) %>% 
  rename(chelsa15 = gfdl_2071_2100_585_bio15)

write.csv(gfdl_2071_2100_585, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/GFDL_ESM4/gfdl_2071_2100_585_extract_updated_names.csv"), row.names = TRUE) 
```

```{r}
### Run MESS
gfdl_2071_2100_585_MESS <- MESS(historic, gfdl_2071_2100_585)

gfdl_2071_2100_585_MESS
```

#### 585 ####
### IPSL_CM6A_LR ###

```{r}
### Call Chelsa Data 
ipsl_2071_2100_585_stack <- stack(paste0(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/IPSL_CM6A_LR/ipsl_2071_2100_585_bio", c("1","2","4","6","7","12","14","15"), ".tif"))

# Extract values
ipsl_2071_2100_585_extract <- raster::extract(ipsl_2071_2100_585_stack, thinned_all_spp_occs_xy)

# save as dataframe
write.csv(ipsl_2071_2100_585_extract, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/IPSL_CM6A_LR/ipsl_2071_2100_585_extract.csv"), row.names = TRUE)
```

```{r}
### Load in dataframe and edit column names

ipsl_2071_2100_585 <- read.csv(here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/IPSL_CM6A_LR/ipsl_2071_2100_585_extract.csv"))

ipsl_2071_2100_585 <- ipsl_2071_2100_585 %>% 
  subset(select = -X) %>% 
  rename(chelsa01 = ipsl_2071_2100_585_bio1) %>% 
  rename(chelsa02 = ipsl_2071_2100_585_bio2) %>% 
  rename(chelsa04 = ipsl_2071_2100_585_bio4) %>% 
  rename(chelsa06 = ipsl_2071_2100_585_bio6) %>% 
  rename(chelsa07 = ipsl_2071_2100_585_bio7) %>% 
  rename(chelsa12 = ipsl_2071_2100_585_bio12) %>% 
  rename(chelsa14 = ipsl_2071_2100_585_bio14) %>% 
  rename(chelsa15 = ipsl_2071_2100_585_bio15)

write.csv(ipsl_2071_2100_585, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/IPSL_CM6A_LR/ipsl_2071_2100_585_extract_updated_names.csv"), row.names = TRUE)
```

```{r}
### Run MESS
ipsl_2071_2100_585_MESS <- MESS(historic, ipsl_2071_2100_585)

ipsl_2071_2100_585_MESS
```

#### 585 ####
### MPI_ESM1_2_HR ###

```{r}
### Call Chelsa Data 
mpi_2071_2100_585_stack <- stack(paste0(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/MPI_ESM1_2_HR/mpi_2071_2100_585_bio", c("1","2","4","6","7","12","14","15"), ".tif"))

# Extract values
mpi_2071_2100_585_extract <- raster::extract(mpi_2071_2100_585_stack, thinned_all_spp_occs_xy)

# save as dataframe
write.csv(mpi_2071_2100_585_extract, paste0(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/MPI_ESM1_2_HR/mpi_2071_2100_585_extract.csv"), row.names = TRUE)
```

```{r}
### Load in dataframe and edit column names

mpi_2071_2100_585 <- read.csv(here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/MPI_ESM1_2_HR/mpi_2071_2100_585_extract.csv"))

mpi_2071_2100_585 <- mpi_2071_2100_585 %>% 
  subset(select = -X) %>% 
  rename(chelsa01 = mpi_2071_2100_585_bio1) %>% 
  rename(chelsa02 = mpi_2071_2100_585_bio2) %>% 
  rename(chelsa04 = mpi_2071_2100_585_bio4) %>% 
  rename(chelsa06 = mpi_2071_2100_585_bio6) %>% 
  rename(chelsa07 = mpi_2071_2100_585_bio7) %>% 
  rename(chelsa12 = mpi_2071_2100_585_bio12) %>% 
  rename(chelsa14 = mpi_2071_2100_585_bio14) %>% 
  rename(chelsa15 = mpi_2071_2100_585_bio15)

write.csv(mpi_2071_2100_585, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/MPI_ESM1_2_HR/mpi_2071_2100_585_extract_updated_names.csv"), row.names = TRUE)
```

```{r}
### Run MESS
mpi_2071_2100_585_MESS <- MESS(historic, mpi_2071_2100_585)

mpi_2071_2100_585_MESS
```

#### 585 ####
### MRI_ESM2_0 ###

```{r}
### Call Chelsa Data 
mri_2071_2100_585_stack <- stack(paste0(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/MRI_ESM2_0/mri_2071_2100_585_bio", c("1","2","4","6","7","12","14","15"), ".tif"))

# Extract values
mri_2071_2100_585_extract <- raster::extract(mri_2071_2100_585_stack, thinned_all_spp_occs_xy)

# save as dataframe
write.csv(mri_2071_2100_585_extract, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/MRI_ESM2_0/mri_2071_2100_585_extract.csv"), row.names = TRUE)
```

```{r}
### Load in dataframe and edit column names

mri_2071_2100_585 <- read.csv(here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/MRI_ESM2_0/mri_2071_2100_585_extract.csv"))

mri_2071_2100_585 <- mri_2071_2100_585 %>% 
  subset(select = -X) %>% 
  rename(chelsa01 = mri_2071_2100_585_bio1) %>% 
  rename(chelsa02 = mri_2071_2100_585_bio2) %>% 
  rename(chelsa04 = mri_2071_2100_585_bio4) %>% 
  rename(chelsa06 = mri_2071_2100_585_bio6) %>% 
  rename(chelsa07 = mri_2071_2100_585_bio7) %>% 
  rename(chelsa12 = mri_2071_2100_585_bio12) %>% 
  rename(chelsa14 = mri_2071_2100_585_bio14) %>% 
  rename(chelsa15 = mri_2071_2100_585_bio15)

write.csv(mri_2071_2100_585, here("/Asia_MESS_analysis/input_dataframes/2071_2100/585/MRI_ESM2_0/mri_2071_2100_585_extract_updated_names.csv"), row.names = TRUE)
```

```{r}
### Run MESS
mri_2071_2100_585_MESS <- MESS(historic, mri_2071_2100_585)

mri_2071_2100_585_MESS
```

#### 585 ####
### UKESM1_0_LL ###

```{r}
### Call Chelsa Data 
ukesm_2071_2100_585_stack <- stack(paste0(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/UKESM1_0_LL/ukesm_2071_2100_585_bio", c("1","2","4","6","7","12","14","15"), ".tif"))

# Extract values
ukesm_2071_2100_585_extract <- raster::extract(ukesm_2071_2100_585_stack, thinned_all_spp_occs_xy)

# save as dataframe
write.csv(ukesm_2071_2100_585_extract, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/UKESM1_0_LL/ukesm_2071_2100_585_extract.csv"), row.names = TRUE)
```

```{r}
### Load in dataframe and edit column names

ukesm_2071_2100_585 <- read.csv(here(HWC_data,"/Asia_MESS_analysis/input_dataframes/2071_2100/585/UKESM1_0_LL/ukesm_2071_2100_585_extract.csv"))

ukesm_2071_2100_585 <- ukesm_2071_2100_585 %>% 
  subset(select = -X) %>% 
  rename(chelsa01 = ukesm_2071_2100_585_bio1) %>% 
  rename(chelsa02 = ukesm_2071_2100_585_bio2) %>% 
  rename(chelsa04 = ukesm_2071_2100_585_bio4) %>% 
  rename(chelsa06 = ukesm_2071_2100_585_bio6) %>% 
  rename(chelsa07 = ukesm_2071_2100_585_bio7) %>% 
  rename(chelsa12 = ukesm_2071_2100_585_bio12) %>% 
  rename(chelsa14 = ukesm_2071_2100_585_bio14) %>% 
  rename(chelsa15 = ukesm_2071_2100_585_bio15)

write.csv(ukesm_2071_2100_585, here(HWC_data, "/Asia_MESS_analysis/input_dataframes/2071_2100/585/UKESM1_0_LL/ukesm_2071_2100_585_extract_updated_names.csv"), row.names = TRUE)
```

```{r}
### Run MESS
ukesm_2071_2100_585_MESS <- MESS(historic, ukesm_2071_2100_585)

ukesm_2071_2100_585_MESS
```

########### Check Individual Change Maps ############## 

```{r}
historic_chelsa1 <- raster(here(HWC_data, "/Data/Chelsa_Data/asia_masked_CHELSA_data/asia_masked_CHELSA_layer01.tif"))

historic_chelsa2 <- raster(here(HWC_data, "/Data/Chelsa_Data/asia_masked_CHELSA_data/asia_masked_CHELSA_layer02.tif"))

historic_chelsa12 <- raster(here(HWC_data, "/Data/Chelsa_Data/asia_masked_CHELSA_data/asia_masked_CHELSA_layer12.tif"))
```

#### 585 ####
### GFDL_ESM4 ###

```{r}
gfdl_2071_2100_585_chelsa1 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/GFDL_ESM4/gfdl_2071_2100_585_bio1.tif"))

gfdl_2071_2100_585_chelsa2 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/GFDL_ESM4/gfdl_2071_2100_585_bio2.tif"))

gfdl_2071_2100_585_chelsa12 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/GFDL_ESM4/gfdl_2071_2100_585_bio12.tif"))
```

### CHELSA 1 ### 

```{r}
gfdl_2071_2100_585_chelsa1_change_map <- gfdl_2071_2100_585_chelsa1 - historic_chelsa1 

#plot(gfdl_2071_2100_585_chelsa1)
#plot(historic_chelsa1)
plot(gfdl_2071_2100_585_chelsa1_change_map)
```

### CHELSA 2 ### 

```{r}
gfdl_2071_2100_585_chelsa2_change_map <- gfdl_2071_2100_585_chelsa2 - historic_chelsa2 

plot(gfdl_2071_2100_585_chelsa2_change_map)
```

### CHELSA 12 ### 

```{r}
gfdl_2071_2100_585_chelsa12_change_map <- gfdl_2071_2100_585_chelsa12 - historic_chelsa12 

plot(gfdl_2071_2100_585_chelsa12_change_map)
```

#### 585 ####
### IPSL_CM6A_LR ###

```{r}
ipsl_2071_2100_585_chelsa1 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/IPSL_CM6A_LR/ipsl_2071_2100_585_bio1.tif"))

ipsl_2071_2100_585_chelsa2 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/IPSL_CM6A_LR/ipsl_2071_2100_585_bio2.tif"))

ipsl_2071_2100_585_chelsa12 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/IPSL_CM6A_LR/ipsl_2071_2100_585_bio12.tif"))
```

### CHELSA 1 ### 

```{r}
ipsl_2071_2100_585_chelsa1_change_map <- ipsl_2071_2100_585_chelsa1 - historic_chelsa1 

#plot(ipsl_2071_2100_585_chelsa1)
#plot(historic_chelsa1)
plot(ipsl_2071_2100_585_chelsa1_change_map)
```

### CHELSA 2 ### 

```{r}
ipsl_2071_2100_585_chelsa2_change_map <- ipsl_2071_2100_585_chelsa2 - historic_chelsa2 

plot(ipsl_2071_2100_585_chelsa2_change_map)
```

### CHELSA 12 ### 

```{r}
ipsl_2071_2100_585_chelsa12_change_map <- ipsl_2071_2100_585_chelsa12 - historic_chelsa12 

plot(ipsl_2071_2100_585_chelsa12_change_map)
```


#### 585 ####
### MPI_ESM1_2_HR ###

```{r}
mpi_2071_2100_585_chelsa1 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/MPI_ESM1_2_HR/mpi_2071_2100_585_bio1.tif"))

mpi_2071_2100_585_chelsa2 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/MPI_ESM1_2_HR/mpi_2071_2100_585_bio2.tif"))

mpi_2071_2100_585_chelsa12 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/MPI_ESM1_2_HR/mpi_2071_2100_585_bio12.tif"))
```

### CHELSA 1 ### 

```{r}
mpi_2071_2100_585_chelsa1_change_map <- mpi_2071_2100_585_chelsa1 - historic_chelsa1 

#plot(mpi_2071_2100_585_chelsa1)
#plot(historic_chelsa1)
plot(mpi_2071_2100_585_chelsa1_change_map)
```

### CHELSA 2 ### 

```{r}
mpi_2071_2100_585_chelsa2_change_map <- mpi_2071_2100_585_chelsa2 - historic_chelsa2 

plot(mpi_2071_2100_585_chelsa2_change_map)
```

### CHELSA 12 ### 

```{r}
mpi_2071_2100_585_chelsa12_change_map <- mpi_2071_2100_585_chelsa12 - historic_chelsa12 

plot(mpi_2071_2100_585_chelsa12_change_map)
```

#### 585 ####
### MRI_ESM2_0 ###

```{r}
mri_2071_2100_585_chelsa1 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/MRI_ESM2_0/mri_2071_2100_585_bio1.tif"))

mri_2071_2100_585_chelsa2 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/MRI_ESM2_0/mri_2071_2100_585_bio2.tif"))

mri_2071_2100_585_chelsa12 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/MRI_ESM2_0/mri_2071_2100_585_bio12.tif"))
```

### CHELSA 1 ### 

```{r}
mri_2071_2100_585_chelsa1_change_map <- mri_2071_2100_585_chelsa1 - historic_chelsa1 

#plot(mri_2071_2100_585_chelsa1)
#plot(historic_chelsa1)
plot(mri_2071_2100_585_chelsa1_change_map)
```

### CHELSA 2 ### 

```{r}
mri_2071_2100_585_chelsa2_change_map <- mri_2071_2100_585_chelsa2 - historic_chelsa2 

plot(mri_2071_2100_585_chelsa2_change_map)
```

### CHELSA 12 ### 

```{r}
mri_2071_2100_585_chelsa12_change_map <- mri_2071_2100_585_chelsa12 - historic_chelsa12 

plot(mri_2071_2100_585_chelsa12_change_map)
```

#### 585 ####
### UKESM1_0_LL ###

```{r}
ukesm_2071_2100_585_chelsa1 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/UKESM1_0_LL/ukesm_2071_2100_585_bio1.tif"))

ukesm_2071_2100_585_chelsa2 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/UKESM1_0_LL/ukesm_2071_2100_585_bio2.tif"))

ukesm_2071_2100_585_chelsa12 <- raster(here(HWC_data, "/R_files/R_output_data/chelsa_asia/2071_2100/585/UKESM1_0_LL/ukesm_2071_2100_585_bio12.tif"))
```

### CHELSA 1 ### 

```{r}
ukesm_2071_2100_585_chelsa1_change_map <- ukesm_2071_2100_585_chelsa1 - historic_chelsa1 

plot(ukesm_2071_2100_585_chelsa1)
plot(historic_chelsa1)
plot(ukesm_2071_2100_585_chelsa1_change_map)
```

### CHELSA 2 ### 

```{r}
ukesm_2071_2100_585_chelsa2_change_map <- ukesm_2071_2100_585_chelsa2 - historic_chelsa2 

plot(ukesm_2071_2100_585_chelsa2_change_map)
```

### CHELSA 12 ### 

```{r}
ukesm_2071_2100_585_chelsa12_change_map <- ukesm_2071_2100_585_chelsa12 - historic_chelsa12 

plot(ukesm_2071_2100_585_chelsa12_change_map)
```