---
title: "Replication of Di Minin 2021 Analysis"
author: "Mia Guarnieri"
date: '2022-10-11'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
```

#Input data

##Range data

```{r}
#turn off spherical geometry to simplify joins, etc.
sf_use_s2(FALSE)

#savanna elephant range (filtered to only keep extant ranges)
sav <- read_sf(here("/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data/Geospatial Data/range_data/iucn_range_sav_elephant/data_0.shp")) %>% 
  filter(LEGEND %in% c("Extant (resident)", "Extant & Reintroduced (resident)", "Possibly Extant (resident)"))

#forest elephant range (filtered to only keep extant ranges)
forest <- read_sf(here("/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data/Geospatial Data/range_data/iucn_range_forest_elephant/data_0.shp")) %>% 
  filter(LEGEND %in% c("Extant (resident)", "Extant & Reintroduced (resident)", "Possibly Extant (resident)"))

#combined range map for savanna and forest elephants
all_elephant_range <- rbind(sav, forest)

#plot combined range
tm_shape(all_elephant_range) +
  tm_polygons(col = "LEGEND") +
  tmap_mode("view")

#plot savanna elephant range
tm_shape(sav) +
  tm_polygons(col = "LEGEND") +
  tmap_mode("view")
```

##World protected areas

```{r}
#world protected areas; divided into 3 sets of polygons and 3 sets of points which need to be merged together to create one polygon layer and one points layer

#polygon layers

wpa_1_pol <- read_sf(here("/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data/Geospatial Data/protected_areas/WDPA_Africa_Oct2022_shp/WDPA_WDOECM_Oct2022_Public_AF_shp_0/WDPA_WDOECM_Oct2022_Public_AF_shp-polygons.shp")) 

wpa_2_pol <- read_sf(here("/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data/Geospatial Data/protected_areas/WDPA_Africa_Oct2022_shp/WDPA_WDOECM_Oct2022_Public_AF_shp_1/WDPA_WDOECM_Oct2022_Public_AF_shp-polygons.shp"))

wpa_3_pol <- read_sf(here("/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data/Geospatial Data/protected_areas/WDPA_Africa_Oct2022_shp/WDPA_WDOECM_Oct2022_Public_AF_shp_2/WDPA_WDOECM_Oct2022_Public_AF_shp-polygons.shp")) 

#combined polygon layer

wpa_all_polygons <- rbind(wpa_1_pol, wpa_2_pol, wpa_3_pol)

#plotted wpa polygon layer

tm_shape(wpa_all_polygons) +
  tm_polygons() +
  tmap_mode("view")

#point data layers

wpa_1_point <- read_sf(here("/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data/Geospatial Data/protected_areas/WDPA_Africa_Oct2022_shp/WDPA_WDOECM_Oct2022_Public_AF_shp_0/WDPA_WDOECM_Oct2022_Public_AF_shp-points.shp"))

wpa_2_point <- read_sf(here("/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data/Geospatial Data/protected_areas/WDPA_Africa_Oct2022_shp/WDPA_WDOECM_Oct2022_Public_AF_shp_1/WDPA_WDOECM_Oct2022_Public_AF_shp-points.shp"))

wpa_3_point <- read_sf(here("/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data/Geospatial Data/protected_areas/WDPA_Africa_Oct2022_shp/WDPA_WDOECM_Oct2022_Public_AF_shp_2/WDPA_WDOECM_Oct2022_Public_AF_shp-points.shp"))

#combined points layer

wpa_all_points <- rbind(wpa_1_point, wpa_2_point, wpa_3_point)

#plotted wpa points layer

tm_shape(wpa_all_points) +
  tm_dots() +
  tmap_mode("view")

#plotted wpa polygon and point layers together
tm_shape(wpa_all_polygons) +
  tm_polygons() +
tm_shape(wpa_all_points) +
  tm_dots() +
  tmap_mode("view")
```

