---
title: "Baseline Pop Exploration"
author: "Mia Guarnieri"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(geos)
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyterra)

#File path to the HWC_data folder

HWC_data <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data"
```

#Read in the data

```{r}
#Worldpop 2010

wp2010 <- rast(here(HWC_data, "/Geospatial Data/Pop_dens/fpop_data/ppp_2010_1km_Aggregated.tif"))

#SSP1
SSP1 <- rast(here(HWC_data, "/Geospatial Data/Pop_dens/fpop_data/FPOP_SSP1/FPOP_SSP1_2020.tif"))
 
#SSP2
SSP2 <- rast(here(HWC_data, "/Geospatial Data/Pop_dens/fpop_data/FPOP_SSP2/FPOP_SSP2_2020.tif"))

#SSP3
SSP3 <- rast(here(HWC_data, "/Geospatial Data/Pop_dens/fpop_data/FPOP_SSP3/FPOP_SSP3_2020.tif"))

#SSP4
SSP4 <- rast(here(HWC_data, "/Geospatial Data/Pop_dens/fpop_data/FPOP_SSP4/FPOP_SSP4_2020.tif"))

#SSP5
SSP5 <- rast(here(HWC_data, "/Geospatial Data/Pop_dens/fpop_data/FPOP_SSP5/FPOP_SSP5_2020.tif"))

#read in necessary data layers for the function

#read in lulc for reprojection
lulc <- rast(here(HWC_data, "/Geospatial Data/Chen_LULC_data/global_LULC_2015.tif"))
  
#read in a ratser for Africa 
  
africa <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/africa_rast/africa_rast.tiff"))
```

```{r}
#save the Africa raster for later processing

writeRaster(africa, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/africa_rast/africa_rast.tif"), filetype = "GTiff", overwrite = TRUE)

```


#Wrangling 

```{r}
#turn off spherical geometry to simplify joins, etc.
sf_use_s2(FALSE)

#Function to aggregate pop density

pop_agg <- function(x){
  
  #reproject the designated population raster
  popdens <- project(x, lulc)
  
  #mask pop density to africa extent
  popdens_africa <- mask(popdens, africa)
  
  #aggregate pop density
  
  africa_popdens_agg <- terra::aggregate(popdens_africa, fact = 10, fun = sum, na.rm = TRUE)
  
  return(africa_popdens_agg)
}


SSP1_agg <- pop_agg(SSP1)

SSP2_agg <- pop_agg(SSP2)

SSP3_agg <- pop_agg(SSP3)

SSP4_agg <- pop_agg(SSP4)

SSP5_agg <- pop_agg(SSP5)

wp2010_agg <- pop_agg(wp2010)
```

```{r}
#saving the aggregated rasters

writeRaster(SSP1_agg, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp1.tif"), filetype = "GTiff", overwrite = TRUE)

writeRaster(SSP2_agg, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp2.tif"), filetype = "GTiff", overwrite = TRUE)

writeRaster(SSP3_agg, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp3.tif"), filetype = "GTiff", overwrite = TRUE)

writeRaster(SSP4_agg, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp4.tif"), filetype = "GTiff", overwrite = TRUE)

writeRaster(SSP5_agg, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp5.tif"), filetype = "GTiff", overwrite = TRUE)

writeRaster(wp2010_agg, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/wp2010_agg.tif"), filetype = "GTiff", overwrite = TRUE)

```


#Run the wrangling function

```{r}
#reading in the saved rasters

ssp1 <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp1.tif"))

ssp2 <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp2.tif"))

ssp3 <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp3.tif"))

ssp4 <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp4.tif"))

ssp5 <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/2020_agg_pop/ssp5.tif"))

wp2010 <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/pop_density/wp2010_agg.tif"))

```


```{r}
#take the difference

ssp1_diff <- ssp1 - wp2010

#min value   :      -97705.66 
#max value   :     1915242.31 

ssp2_diff <- ssp2 - wp2010

# min value   :      -98834.27 
# max value   :      454501.91 

ssp3_diff <- ssp3 - wp2010

# min value   :      -96657.59 
# max value   :      466582.34 

ssp4_diff <- ssp4 - wp2010

# min value   :      -97658.98 
# max value   :      461080.28 

ssp5_diff <- ssp5 - wp2010

# min value   :       -97879.8 
# max value   :       459688.4 

```

```{r}
#test plots 

#create a basemap

basemap_africa <- ne_countries(
  continent = "Africa",
  scale = "medium", 
  returnclass = "sf") %>% 
  st_transform(crs = crs(ssp1_diff))  # make sure crs is same as raster

basemap_africa_vect <- basemap_africa %>% 
  vect()

#map pop density difference rasters

#combine all plots into one graphic
par(mfrow=c(2,3))

#SSP1
plot(basemap_africa_vect, col = "grey98")
plot(ssp1_diff, add = TRUE)

#SSP2
plot(basemap_africa_vect, col = "grey98")
plot(ssp2_diff, add = TRUE)

#SSP3
plot(basemap_africa_vect, col = "grey98")
plot(ssp3_diff, add = TRUE)

#SSP4
plot(basemap_africa_vect, col = "grey98")
plot(ssp2_diff, add = TRUE)

#SSP5
plot(basemap_africa_vect, col = "grey98")
plot(ssp5_diff, add = TRUE)
```


#Plot

```{r}
#test plots for human population density layers

#create a basemap

basemap_africa <- ne_countries(
  continent = "Africa",
  scale = "medium", 
  returnclass = "sf") %>% 
  st_transform(crs = crs(SSP1_wrangled))  # make sure crs is same as raster

basemap_africa_vect <- basemap_africa %>% 
  vect()

#map pop density rasters

#combine all plots into one graphic
par(mfrow=c(2,3))

#SSP1
plot(basemap_africa_vect, col = "grey98")
plot(ssp1_diff, add = TRUE, col = "darkgreen")

#SSP2
plot(basemap_africa_vect, col = "grey98")
plot(ssp2_diff, add = TRUE, col = "darkseagreen4")

#SSP3
plot(basemap_africa_vect, col = "grey98")
plot(ssp3_diff, add = TRUE, col = "goldenrod1")

#SSP4
plot(basemap_africa_vect, col = "grey98")
plot(ssp4_diff, add = TRUE, col = "orange1")

#SSP5
plot(basemap_africa_vect, col = "grey98")
plot(ssp5_diff, add = TRUE, col = "orangered")

```

