---
title: "Ranked Conflict Maps Asia"
author: "Grace Kumaishi"
date: "1/17/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(geos)
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyterra)

#File path to the HWC_data folder

#HWC_data <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data"

#Mia's file path

HWC_data <- "/Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/My Drive/Arnhold Project/HWC_data"

```

Years: 2030, 2050, 2070

#Boundary lines - outdated; maybe delete

#SSP 1 RCP 2.6

##2030
```{r}
ssp <- 1

year <- 2030

rcp <- 26

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

##2050
```{r}
ssp <- 1

year <- 2050

rcp <- 26

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

##2070
```{r}
ssp <- 1

year <- 2070

rcp <- 26

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

#SSP 2 RCP 4.5

##2030
```{r}
ssp <- 2

year <- 2030

rcp <- 45

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

##2050
```{r}
ssp <- 2

year <- 2050

rcp <- 45

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

##2070
```{r}
ssp <- 2

year <- 2070

rcp <- 45

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```


#SSP 3 RCP 7.0 

##2030
```{r}
ssp <- 3

year <- 2030

rcp <- 70

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```


##2050
```{r}
ssp <- 3

year <- 2050

rcp <- 70

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```


##2070
```{r}
ssp <- 3

year <- 2070

rcp <- 70

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```


#SSP 4 RCP 6.0 


##2030
```{r}
ssp <- 4

year <- 2030

rcp <- 60

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

##2050
```{r}
ssp <- 4

year <- 2050

rcp <- 60

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

##2070
```{r}
ssp <- 4

year <- 2070

rcp <- 60

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```


#SSP 5 RCP 8.5

##2030
```{r}
ssp <- 5

year <- 2030

rcp <- 85

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

##2050
```{r}
ssp <- 5

year <- 2050

rcp <- 85

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

##2070
```{r}
ssp <- 5

year <- 2070

rcp <- 85

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_script_asia.rmd"), quiet = TRUE))
```

#Boundary rasters

#SSP 1 RCP 2.6

##2030
```{r}
ssp <- 1

year <- 2030

rcp <- 26

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```

##2050
```{r}
ssp <- 1

year <- 2050

rcp <- 26

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```

##2070
```{r}
ssp <- 1

year <- 2070

rcp <- 26

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```


#SSP 2 RCP 4.5

##2030
```{r}
ssp <- 2

year <- 2030

rcp <- 45

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```

##2050
```{r}
ssp <- 2

year <- 2050

rcp <- 45

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```

##2070
```{r}
ssp <- 2

year <- 2070

rcp <- 45

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```


#SSP 3 RCP 7.0 

##2030
```{r}
ssp <- 3

year <- 2030

rcp <- 70

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```


##2050
```{r}
ssp <- 3

year <- 2050

rcp <- 70

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```


##2070
```{r}
ssp <- 3

year <- 2070

rcp <- 70

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```



#SSP 4 RCP 6.0 


##2030
```{r}
ssp <- 4

year <- 2030

rcp <- 60

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```

##2050
```{r}
ssp <- 4

year <- 2050

rcp <- 60

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```

##2070
```{r}
ssp <- 4

year <- 2070

rcp <- 60

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```


#SSP 5 RCP 8.5

##2030
```{r}
ssp <- 5

year <- 2030

rcp <- 85

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```

##2050
```{r}
ssp <- 5

year <- 2050

rcp <- 85

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```

##2070
```{r}
ssp <- 5

year <- 2070

rcp <- 85

source(knitr::purl(here("DiMinin_replication_Asia", "conflict_boundary_raster_script_asia.rmd"), quiet = TRUE))
```


#Conflict Boundary Polygons

```{r}
confpol <- function(x){
  
  #read in the raster
  
  conf_rast <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/conflict_boundaries/conflict_boundary_rasters_asia/", x))
  
  #turn the raster layer into polygons
  
  cb_vect <- terra::as.polygons(conf_rast, dissolve=TRUE, values=TRUE, na.rm=TRUE, na.all=FALSE, extent=FALSE) %>% 
    st_as_sf()
  
  st_write(cb_vect, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/conflict_boundaries/conflict_boundary_polygons_asia/", name), append = FALSE)
}

rast_list <- list.files(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/conflict_boundaries/conflict_boundary_rasters_asia"))


for (i in rast_list) {
  
  name <- str_replace(i, ".tif", ".shp")
  
  confpol(i)
  
}

```










