---
title: "Conflict Boundary Explanation Asia"
author: "Grace Kumaishi"
date: "1/25/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(terra)
library(sf)
library(tmap)
library(geos)
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyterra)
library(kableExtra)

#File path to the HWC_data folder

#HWC_data <- "/Volumes/GoogleDrive/.shortcut-targets-by-id/1YB-Hz3L-kWyiZMg2UM89GQkvqXyZUW1H/HWC_data"

#Mia's file path

HWC_data <- "/Users/mia/Library/CloudStorage/GoogleDrive-mguarnieri@ucsb.edu/My Drive/Arnhold Project/HWC_data"
```

#Create differenced rasters

```{r}
# make a function to read in the designated raster, difference it from baseline, and save it

rast_diff <- function(x){
  
  proj <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/conflict_boundaries/conflict_boundary_rasters_asia", x))
  
  base <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/conflict_boundaries/conflict_boundary_rasters_asia/wp2010_current_day_cb_raster_asia.tif"))
  
  diff <- proj - base
  
  writeRaster(diff, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_conflict/differenced_rasters_asia/", name), overwrite = TRUE)
}

#create a list of all files that need to be differenced and saved

rast_files <- list.files(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/conflict_boundaries/conflict_boundary_rasters_asia"))


for (i in rast_files) {
  
  file <- i
  
  name <- paste0("diff_", file)
  
  rast_diff(i)
  
}


```


#Polygonize difference rasters for visualization

Polyline - outdated, maybe delete?

```{r}

#polyline function

poly <- function(x){
  #first make it a spatvector
  current_cb_vect <- terra::as.polygons(x, trunc=TRUE, dissolve=TRUE, values=TRUE,
    na.rm=TRUE, extent=FALSE) #removed na.all = FALSE
  
  #then turn that into a polyline
  current_cb_line <- st_as_sf(current_cb_vect) %>% 
    st_cast("MULTILINESTRING")
  
  return(current_cb_line)
}

#ssp1

ssp1_2030_diff_poly <- poly(ssp1_rcp26_2030_diff)
ssp1_2050_diff_poly <- poly(ssp1_rcp26_2050_diff)
ssp1_2070_diff_poly <- poly(ssp1_rcp26_2070_diff)

#ssp2

ssp2_2030_diff_poly <- poly(ssp2_rcp45_2030_diff)
ssp2_2050_diff_poly <- poly(ssp2_rcp45_2050_diff)
ssp2_2070_diff_poly <- poly(ssp2_rcp45_2070_diff)

#ssp3

ssp3_2030_diff_poly <- poly(ssp3_rcp70_2030_diff)
ssp3_2050_diff_poly <- poly(ssp3_rcp70_2050_diff)
ssp3_2070_diff_poly <- poly(ssp3_rcp70_2070_diff)

#ssp4

ssp4_2030_diff_poly <- poly(ssp4_rcp60_2030_diff)
ssp4_2050_diff_poly <- poly(ssp4_rcp60_2050_diff)
ssp4_2070_diff_poly <- poly(ssp4_rcp60_2070_diff)

#ssp5

ssp5_2030_diff_poly <- poly(ssp5_rcp85_2030_diff)
ssp5_2050_diff_poly <- poly(ssp5_rcp85_2050_diff)
ssp5_2070_diff_poly <- poly(ssp5_rcp85_2070_diff)

#save polylines for use in GIS

#ssp1
st_write(ssp1_2030_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp1_rcp26_2030_diff.shp"), append = FALSE)

st_write(ssp1_2050_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp1_rcp26_2050_diff.shp"), append = FALSE)

st_write(ssp1_2070_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp1_rcp26_2070_diff.shp"), append = FALSE)

#ssp2

st_write(ssp2_2030_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp2_rcp45_2030_diff.shp"), append = FALSE)

st_write(ssp2_2050_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp2_rcp45_2050_diff.shp"), append = FALSE)

st_write(ssp2_2070_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp2_rcp45_2070_diff.shp"), append = FALSE)

#ssp3

st_write(ssp3_2030_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp3_rcp70_2030_diff.shp"), append = FALSE)

st_write(ssp3_2050_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp3_rcp70_2050_diff.shp"), append = FALSE)

st_write(ssp3_2070_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp3_rcp70_2070_diff.shp"), append = FALSE)

#ssp4

st_write(ssp4_2030_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp4_rcp60_2030_diff.shp"), append = FALSE)

st_write(ssp4_2050_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp4_rcp60_2050_diff.shp"), append = FALSE)

st_write(ssp4_2070_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp4_rcp60_2070_diff.shp"), append = FALSE)

#ssp5

st_write(ssp5_2030_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp5_rcp85_2030_diff.shp"), append = FALSE)

st_write(ssp5_2050_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp5_rcp85_2050_diff.shp"), append = FALSE)

st_write(ssp5_2070_diff_poly, dsn = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp5_rcp85_2070_diff.shp"), append = FALSE)


#test plot:
#create a basemap

basemap_asia <- ne_countries(
  continent = "Asia",
  scale = "medium", 
  returnclass = "sf") %>% 
  st_transform(crs = crs(ssp3_2050_diff_poly))  # make sure crs is same as raster

basemap_asia_vect <- basemap_asia %>% 
  vect()

#plot conflict boundaries

#pal <- c("darkgreen", "goldenrod", "orangered")


plot(basemap_asia_vect, col = "grey98")
plot(ssp3_2050_diff_poly, add = TRUE, legend = TRUE)

```

#Polygons

```{r}

polygons <- function(x){
  
  pol <- rast(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_conflict/differenced_rasters_asia/", x)) %>%
    terra::as.polygons(dissolve=TRUE, values=TRUE, na.rm=TRUE, na.all=FALSE, extent=FALSE)
 
  writeVector(pol, filename = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_conflict/differenced_polygons_asia/", name), overwrite = TRUE)
  
}

diff_rasts <- list.files(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_conflict/differenced_rasters_asia"))


for (i in diff_rasts) {
  
  file <- str_remove(i, ".tif")
  
  name <- paste0(file, "_polygon.shp")
  
  polygons(i)
  
}

```


#Percent value calculations

##Read in initial polyline and polygon files

Polylines - outdated; maybe delete?

```{r polylines}
#Polylines

#SSP1
ssp1_2030_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp1_rcp26_2030_diff.shp"))

ssp1_2050_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines_asia/ssp1_rcp26_2050_diff.shp"))

ssp1_2070_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp1_rcp26_2070_diff.shp"))


#SSP2

ssp2_2030_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp2_rcp45_2030_diff.shp"))

ssp2_2050_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp2_rcp45_2050_diff.shp"))

ssp2_2070_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp2_rcp45_2070_diff.shp"))


#SSP3

ssp3_2030_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp3_rcp70_2030_diff.shp"))

ssp3_2050_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp3_rcp70_2050_diff.shp"))

ssp3_2070_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp3_rcp70_2070_diff.shp"))


#SSP4

ssp4_2030_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp4_rcp60_2030_diff.shp"))

ssp4_2050_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp4_rcp60_2050_diff.shp"))

ssp4_2070_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp4_rcp60_2070_diff.shp"))


#SSP5

ssp5_2030_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp5_rcp85_2030_diff.shp"))

ssp5_2050_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp5_rcp85_2050_diff.shp"))

ssp5_2070_lines <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_polylines/ssp5_rcp85_2070_diff.shp"))

```

Polygons:

```{r}
#Polygons

#SSP1

ssp1_2050_polygons <- vect(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_conflict/differenced_polygons_asia/diff_SSP1_RCP26_2050_polygon.shp"))


#SSP3

ssp3_2050_polygons <- vect(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_conflict/differenced_polygons_asia/diff_SSP3_RCP70_2050_polygon.shp"))

```

##Set up function for percentage area/length calculations

```{r}
perc_area_table <- function(x){
  
  diff_pol <- read_sf(here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_conflict/differenced_polygons_asia/", x))
  
  colnames(diff_pol) = c("conflict_change", "geometry")
  
  table <- diff_pol %>% 
    as.data.frame() %>% 
    mutate(area = st_area(diff_pol, unit = "m")) %>% 
    mutate(perc_area = (area/sum(area) * 100)) %>% 
    select(conflict_change, perc_area)
  
  return(table)
}

perc_length_table <- function(x){
  
  colnames(x) = c("class", "geometry")
  
  cb_area_table <- x %>% 
    rowwise() %>%
    mutate(length = st_length(geometry)) %>%
    ungroup() %>%
    group_by(class) %>%
    summarize(length = as.numeric(sum(length))) %>%
    ungroup() %>% 
    as.data.frame() %>% 
    mutate(perc_length = (length/sum(length) * 100))
  
  return(cb_area_table)
}

```

##Run calculations

###Lines - outdated; maybe delete?

```{r}

#SSP1
s1_2030_diff_table <- perc_length_table(ssp1_2030_lines)

s1_2050_diff_table <- perc_length_table(ssp1_2050_lines)

s1_2070_diff_table <- perc_length_table(ssp1_2070_lines)


#SSP2
s2_2030_diff_table <- perc_length_table(ssp2_2030_lines)

s2_2050_diff_table <- perc_length_table(ssp2_2050_lines)

s2_2070_diff_table <- perc_length_table(ssp2_2070_lines)


#SSP3
s3_2030_diff_table <- perc_length_table(ssp3_2030_lines)

s3_2050_diff_table <- perc_length_table(ssp3_2050_lines)

s3_2070_diff_table <- perc_length_table(ssp3_2070_lines)


#SSP4
s4_2030_diff_table <- perc_length_table(ssp4_2030_lines)

s4_2050_diff_table <- perc_length_table(ssp4_2050_lines)

s4_2070_diff_table <- perc_length_table(ssp4_2070_lines)


#SSP5
s5_2030_diff_table <- perc_length_table(ssp5_2030_lines)

s5_2050_diff_table <- perc_length_table(ssp5_2050_lines)

s5_2070_diff_table <- perc_length_table(ssp5_2070_lines)


#Combined table

conf_change_table <- cbind(
  s1_2030_diff_table$class, 
  
  s1_2030_diff_table$perc_length,
  s2_2030_diff_table$perc_length,
  s3_2030_diff_table$perc_length,
  s4_2030_diff_table$perc_length,
  s5_2030_diff_table$perc_length,
  
  s1_2050_diff_table$perc_length,
  s2_2050_diff_table$perc_length,
  s3_2050_diff_table$perc_length,
  s4_2050_diff_table$perc_length,
  s5_2050_diff_table$perc_length,
  
  s1_2070_diff_table$perc_length,
  s2_2070_diff_table$perc_length,
  s3_2070_diff_table$perc_length,
  s4_2070_diff_table$perc_length,
  s5_2070_diff_table$perc_length
  )

colnames(conf_change_table) = c(
  "Conflict Change", 
  
  "SSP1 2030", 
  "SSP2 2030",
  "SSP3 2030",
  "SSP4 2030",
  "SSP5 2030",
  
  "SSP1 2050",
  "SSP2 2050",
  "SSP3 2050",
  "SSP4 2050",
  "SSP5 2050",
  
  "SSP1 2070",
  "SSP2 2070",
  "SSP3 2070",
  "SSP4 2070",
  "SSP5 2070"
  )

write.csv(conf_change_table, file = here(HWC_data, "Data/Di Minin HWC", "conflict_change_lines_byyear.csv"), row.names=FALSE)
```

```{r}

conf_change_table <- read_csv(here(HWC_data, "Data/Di Minin HWC", "conflict_change_lines_byyear.csv"))

dec <- c(rep(2, each = 16))

align <- c(rep("c", each = 16))

conf_change_lines_nicetables <- conf_change_table %>%
  kable(digits = dec,
        escape = FALSE,
        align = align) %>% 
  kable_styling(full_width = FALSE, position = "center") %>% 
  add_header_above(c(" ", "2030" = 5, "2050" = 5, "2070" = 5), background = c("#a8e6cf", "#dcedc1", "#ffd3b6")) %>% 
  column_spec(2:6, background = "#a8e6cf") %>%
  column_spec(7:11, background = "#dcedc1") %>% 
  column_spec(12:16, background = "#ffd3b6")

conf_change_lines_nicetables

library(magick)

save_kable(conf_change_lines_nicetables, file = here("/Users/mia/Desktop/Fellowships/Arnhold HWC/conf_change_lines_table_byyear.jpeg"))

```



##Polygons

```{r}
#list all of the files

pol_list_asia <- list.files(path = here(HWC_data, "/Geospatial Data/Diminin_Replication_Data/differenced_conflict/differenced_polygons_asia"), pattern = '.shp')

#apply the area over the list

area_list_asia <- lapply(pol_list_asia, perc_area_table)

conf_change_table_pol_asia <- area_list_asia %>% reduce(full_join, by = "conflict_change") %>% 
  units::drop_units()

colnames(conf_change_table_pol_asia) = c(
  "Conflict Change", 
  
  "SSP1 2030", 
  "SSP1 2050",
  "SSP1 2070",
  
  
  "SSP2 2030",
  "SSP2 2050",
  "SSP2 2070",
  
  
  "SSP3 2030",
  "SSP3 2050",
  "SSP3 2070",
  
  
  "SSP4 2030",
  "SSP4 2050",
  "SSP4 2070",
  
  
  "SSP5 2030",
  "SSP5 2050",
  "SSP5 2070"
  )

write.csv(as.data.frame(conf_change_table_pol_asia), file = here(HWC_data, "Data/Di Minin HWC", "conflict_change_polygons_byssp_asia.csv"), row.names=FALSE)

```


```{r}
#sort by year rather than SSP

conf_change_table_pol_asia_year <- as.data.frame(conf_change_table_pol_asia) %>% 
  dplyr::select(
  "Conflict Change", 
  
  "SSP1 2030", 
  "SSP2 2030",
  "SSP3 2030",
  "SSP4 2030",
  "SSP5 2030",
  
  "SSP1 2050",
  "SSP2 2050",
  "SSP3 2050",
  "SSP4 2050",
  "SSP5 2050",
  
  "SSP1 2070",
  "SSP2 2070",
  "SSP3 2070",
  "SSP4 2070",
  "SSP5 2070"
  )

write.csv(conf_change_table_pol_asia_year, file = here(HWC_data, "Data/Di Minin HWC", "conflict_change_polygons_byyear_asia.csv"), row.names=FALSE)

```

```{r}
conf_change_table_pol_asia_year <- read_csv(here(HWC_data, "Data/Di Minin HWC", "conflict_change_polygons_byyear_asia.csv")) %>% 
  janitor::clean_names() %>% 
  arrange(conflict_change)

colnames(conf_change_table_pol_asia_year) = c(
  "Conflict Change", 
  
  "SSP1 2030", 
  "SSP2 2030",
  "SSP3 2030",
  "SSP4 2030",
  "SSP5 2030",
  
  "SSP1 2050",
  "SSP2 2050",
  "SSP3 2050",
  "SSP4 2050",
  "SSP5 2050",
  
  "SSP1 2070",
  "SSP2 2070",
  "SSP3 2070",
  "SSP4 2070",
  "SSP5 2070"
)

dec <- c(rep(2, each = 16))

align <- c(rep("c", each = 16))

conf_change_pols_nicetable <- conf_change_table_pol_asia_year %>%
  kable(digits = dec,
        escape = FALSE,
        align = align,
        caption = "<center><strong>Percentage of Conflict Boundary Within Each Change Category for Asian Elephants</strong></center>") %>% 
  kable_styling(full_width = FALSE, position = "center") %>% 
  add_header_above(c(" ", "2030" = 5, "2050" = 5, "2070" = 5), background = c("#ffd3b6", "#a8e6cf", "#dcedc1")) %>% 
  column_spec(2:6, background = "#a8e6cf") %>%
  column_spec(7:11, background = "#dcedc1") %>% 
  column_spec(12:16, background = "#ffd3b6")

conf_change_pols_nicetable

library(magick)

save_kable(conf_change_pols_nicetable, file = here("/Users/mia/Desktop/Fellowships/Arnhold HWC/conf_change_polygons_table_byyear_asia.jpeg"), zoom = 2.5)
```

```{r}
conf_change_table_s1s3 <- read_csv(here(HWC_data, "Data/Di Minin HWC", "conflict_change_polygons_byyear_asia.csv")) %>% 
  janitor::clean_names() %>% 
  arrange(conflict_change) %>% 
  mutate("conflict_change" = c("Strong Decrease", "Moderate Decrease", "No Change", "Moderate Increase", "Strong Increase")) %>% 
  select(conflict_change, ssp1_2050, ssp3_2050)

colnames(conf_change_table_s1s3) = c("Conflict Change", "SSP 1 - RCP 2.6", "SSP 3 - RCP 7.0")

dec <- c(rep(2, each = 3))

align <- c(rep("c", each = 3))

conf_change_s1s3_nicetable <- conf_change_table_s1s3 %>%
  kable(digits = dec,
        escape = FALSE,
        align = align) %>% 
  kable_styling(full_width = FALSE, position = "center") %>% 
  column_spec(2, background = "#a8e6cf") %>%
  column_spec(3, background = "#ffd3b6")

conf_change_s1s3_nicetable

library(magick)

save_kable(conf_change_s1s3_nicetable, file = here("/Users/mia/Desktop/Fellowships/Arnhold HWC/current_figures/conf_change_s1s3_asia.jpeg"), zoom = 2.5)
```

