---
title: "Elephant Namibia Tracking Data"
author: "Roshni Katrak-Adefowora"
date: "4/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(maptools)
library(lubridate)

#HWC data file path (# Enter file path to YOUR HWC_data folder, including "HWC_data")
hwc_data <- "I:/My Drive/HWC_data"
```

```{r}
#read in and wrangle namibia sightings
elephant_sightings <- read_xlsx(here(hwc_data, "R_files/R_input_data/namibia/Sightings.xlsx")) %>% 
  clean_names() %>% 
  dplyr::select(x, y, name, d) %>% 
  filter(name %in% c("ElephantFamily", "ElephantBull", "Elephant spoor")) %>% 
  mutate(date = ymd_hms(d))

#read in transect data
transects <- read_xlsx(here(hwc_data, "R_files/R_input_data/namibia/Transects.xlsx"))

#read in gbif occurrences
elephant_gbif <- read_csv(here(hwc_data, "R_files/R_output_data/occurrence_points/savanna_elephant_chelsa_points_thinned_date.csv")) %>% 
  rename(date = eventDate) %>%
  mutate(date = ymd(date)) %>% 
  mutate(month = month(date),
         year = year(date),
         season = month)

elephant_gbif$season[elephant_gbif$season %in% c(1:3, 11:12)] <- "wet"
elephant_gbif$season[elephant_gbif$season %in% c(4:10)] <- "dry"
```


```{r}
#plot points
(data("wrld_simpl"))

# GBIF sightings (run plot and points function at once)
plot(wrld_simpl, 
     xlim = range(elephant_gbif$longitude, na.rm=TRUE),
     ylim = range(elephant_gbif$latitude, na.rm=TRUE), 
     axes = TRUE, 
     col = "light yellow"
     )
points(elephant_gbif$longitude, elephant_gbif$latitude, col = 'blue', pch = 20, cex = 0.75) #add the points

# GBIF sightings zoomed in (run plot and points function at once)
plot(wrld_simpl, 
     xlim = range(elephant_sightings$x, na.rm=TRUE),
     ylim = range(elephant_sightings$y, na.rm=TRUE), 
     axes = TRUE, 
     col = "light yellow"
     )
points(elephant_gbif$longitude, elephant_gbif$latitude, col = 'blue', pch = 20, cex = 0.75) #add the points

# Namibia sightings (run plot and points function at once)
plot(wrld_simpl, 
     xlim = range(elephant_gbif$longitude, na.rm=TRUE),
     ylim = range(elephant_gbif$latitude, na.rm=TRUE), 
     axes = TRUE, 
     col = "light yellow"
     )
points(elephant_sightings$x, elephant_sightings$y, col = 'blue', pch = 20, cex = 0.75) #add the points

# Namibia sightings zoomed in (run plot and points function at once)
plot(wrld_simpl, 
     xlim = range(elephant_sightings$x, na.rm=TRUE),
     ylim = range(elephant_sightings$y, na.rm=TRUE), 
     axes = TRUE, 
     col = "light yellow"
     )
points(elephant_sightings$x, elephant_sightings$y, col = 'blue', pch = 20, cex = 0.75) #add the points
```

```{r}
#make histograms of dates

#namibia sightings
ggplot(data = elephant_sightings, aes(date))+
  geom_histogram(fill = "springgreen4", color = "black")+
  theme_bw()+
  labs(x = "Date (2019)",
       y = "Count",
       title = "Namibia occurrences")+
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 20))+
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 225))

#gbif data
ggplot(data = elephant_gbif, aes(date))+
  geom_histogram(fill = "springgreen4", color = "black")+
  theme_bw()+
  labs(x = "Date (1981-2010)",
       y = "Count",
       title = "GBIF occurrences by year")+
  theme(plot.title = element_text(hjust = 0.5))+
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 125))

ggplot(data = elephant_gbif, aes(month))+
  geom_histogram(fill = "springgreen4", color = "black")+
  theme_bw()+
  labs(x = "Date (Months)",
       y = "Count",
       title = "GBIF occurrences by month")+
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 20))+
  scale_x_continuous(breaks = c(1:12))+
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 100))+
  facet_wrap(~year)

  
ggplot(data = elephant_gbif, aes(season))+
  geom_histogram(stat = "count", fill = "springgreen4")+
  theme_bw()+
  labs(x = "Season",
       y = "Count",
       title = "GBIF occurrences by season")+
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 20))
```

# 2013 - 2019 Namibia tracking data
```{r}
namibia_2013_2019 <- read_csv(here(hwc_data, "R_files/R_input_data/namibia/For mapping 2013 to 2019.csv")) %>% 
  clean_names() %>% 
  filter(grepl('Elephant|elephant', name)) %>% 
  mutate(date = mdy(date),
         month = month(date),
         season = month)

namibia_2013_2019$season[namibia_2013_2019$season %in% c(1:3, 11:12)] <- "wet"
namibia_2013_2019$season[namibia_2013_2019$season %in% c(4:10)] <- "dry"
```

```{r}
#2013: data only collected during dry season
#2014: data only collected during dry season
#2015: data collected february (wet) and september (dry)
#2019: data only collected during dry season

namibia_2015 <- namibia_2013_2019 %>% 
  filter(year == 2015)

#plot data, monthly, wet vs dry season
ggplot(data = namibia_2015, aes(month))+
  geom_histogram()+
  theme_bw()+
  scale_x_continuous(breaks = c(1:12))

ggplot(data = namibia_2015, aes(season))+
  geom_histogram(fill = "springgreen4", color = "black", stat = "count")+
  theme_bw()+
  labs(x = "Season",
       y = "Count",
       title = "Namibia 2015 occurrences by season")

namibia_dry <- namibia_2015 %>% 
  filter(season == "dry")

namibia_wet <- namibia_2015 %>% 
  filter(season == "wet")

# Namibia sightings zoomed in (run plot and points function at once)
(data("wrld_simpl"))

plot(wrld_simpl, 
     xlim = range(namibia_2013_2019$x, na.rm=TRUE),
     ylim = range(namibia_2013_2019$y, na.rm=TRUE), 
     axes = TRUE, 
     col = "light yellow"
     )
points(namibia_dry$x, namibia_dry$y, col = 'blue', pch = 20, cex = 0.75) #add the points

plot(wrld_simpl, 
     xlim = range(namibia_2013_2019$x, na.rm=TRUE),
     ylim = range(namibia_2013_2019$y, na.rm=TRUE), 
     axes = TRUE, 
     col = "light yellow"
     )
points(namibia_wet$x, namibia_wet$y, col = 'blue', pch = 20, cex = 0.75) #add the points
```
